2020-07-13 00:00:18,822 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:00:18,840 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:00:18,840 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:00:22,687 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 00:00:22,904 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:00:27,734 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:00:27,778 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:00:41,397 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> SqlSugar.SqlSugarException: English Message : Connection open error . The ConnectionString property has not been initialized.
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：The ConnectionString property has not been initialized..
   at SqlSugar.AdoProvider.GetDataReader(String sql, SugarParameter[] parameters)
   at SqlSugar.QueryableProvider`1.GetData[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToList[TResult]()
   at SqlSugar.QueryableProvider`1.ToList()
   at SqlSugar.QueryableProvider`1.First()
   at Lazynet.DB.DAL.UserBaseInfoDal.Get(String userName) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.DB\DAL\UserBaseInfoDal.cs:line 28
   at Lazynet.DB.BLL.UserBaseInfoBll.Login(String userName, String password) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.DB\BLL\UserBaseInfoBll.cs:line 34
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:04:16,607 [1] ERROR InfoLogger - System.Exception: load lua file failed
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 52
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename, String rootDirectory) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 63
   at Lazynet.LoginApp.LazynetAppManager.Builder() in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppManager.cs:line 72
2020-07-13 00:04:52,028 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:04:52,047 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:04:52,048 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:04:55,858 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 00:04:56,126 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:05:12,848 [1] ERROR InfoLogger - System.Exception: load lua file failed
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 52
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename, String rootDirectory) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 63
   at Lazynet.LoginApp.LazynetAppManager.Builder() in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppManager.cs:line 72
2020-07-13 00:05:54,007 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:05:54,024 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:05:54,025 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:05:58,146 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 00:05:58,380 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:06:01,617 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:01,663 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:01,812 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:20,150 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:20,151 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:20,178 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:31,033 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:31,037 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:31,062 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:39,553 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:39,554 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:39,578 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:39,800 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:39,806 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:39,832 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:40,033 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:40,035 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:40,067 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:40,253 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:40,254 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:40,278 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:40,479 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:40,480 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:40,505 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:40,680 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:40,681 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:40,707 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:41,246 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:41,248 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:41,273 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:41,577 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:41,578 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:41,603 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:42,044 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:42,045 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:42,070 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:06:55,601 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:06:55,601 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:06:55,624 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:07:24,847 [1] ERROR InfoLogger - System.Exception: load lua file failed
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 52
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename, String rootDirectory) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 63
   at Lazynet.LoginApp.LazynetAppManager.Builder() in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppManager.cs:line 72
2020-07-13 00:07:48,008 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:07:48,031 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:07:48,031 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:07:52,163 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 00:07:52,400 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:07:56,037 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:07:56,078 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:07:56,185 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:08:35,466 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:08:35,487 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:08:35,487 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:08:39,582 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 00:08:39,834 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:08:43,052 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:08:43,094 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:08:43,215 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:08:58,078 [8] ERROR InfoLogger - System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
2020-07-13 00:08:58,098 [8] INFO  InfoLogger - 断开连接
2020-07-13 00:09:20,604 [1] ERROR InfoLogger - System.Exception: load lua file failed
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 52
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename, String rootDirectory) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 63
   at Lazynet.LoginApp.LazynetAppManager.Builder() in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppManager.cs:line 72
2020-07-13 00:10:16,079 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:10:16,097 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:10:16,097 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:10:20,063 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 00:10:20,287 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:10:24,498 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:10:24,539 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:10:24,672 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:47:31,923 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:47:31,939 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:47:31,940 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:47:36,077 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 00:47:36,301 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:48:01,183 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:48:01,231 [6] INFO  InfoLogger - liwei:123456
2020-07-13 00:48:01,344 [6] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:48:18,326 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:51:28,458 [1] ERROR InfoLogger - System.Exception: load lua file failed
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 52
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename, String rootDirectory) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 63
   at Lazynet.LoginApp.LazynetAppManager.Builder() in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppManager.cs:line 72
2020-07-13 00:59:13,247 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:59:13,268 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:59:13,268 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:59:17,246 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 00:59:17,484 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:59:21,560 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:59:21,610 [8] INFO  InfoLogger - liwei:123456
2020-07-13 00:59:21,721 [8] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:59:33,943 [8] ERROR InfoLogger - System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
2020-07-13 00:59:33,968 [8] INFO  InfoLogger - 断开连接
2020-07-13 00:59:42,075 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:59:42,094 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 00:59:42,094 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 00:59:46,075 [7] INFO  InfoLogger - 连接上服务器
2020-07-13 00:59:46,328 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 00:59:49,364 [7] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 00:59:49,407 [7] INFO  InfoLogger - liwei:123456
2020-07-13 00:59:49,516 [7] ERROR InfoLogger - System.Reflection.TargetInvocationException: Failed to call '/User/Login'. ---> Neo.IronLua.LuaRuntimeException: Object is nil.
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda(Closure , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   --- End of inner exception stack trace ---
   at Neo.IronLua.LuaTable.CallMemberDirect(String memberName, Object[] args, Boolean ignoreCase, Boolean rawGet, Boolean throwExceptions, Boolean ignoreNilFunction) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2833
   at Neo.IronLua.LuaTable.CallMember(String memberName, Object[] args) in C:\Projects\NeoLua\NeoLua\LuaTable.cs:line 2765
   at Lazynet.Core.Service.LazynetLuaService.CallBack(LazynetActionEntity message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\Service\LazynetLuaService.cs:line 17
   at Lazynet.AppCore.LazynetAppService.CallService(LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.AppCore\LazynetAppService.cs:line 112
   at Lazynet.LoginApp.LazynetAppServerHandler.CallService(LazynetHandlerContext ctx, LazynetMessage message) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppServerHandler.cs:line 77
2020-07-13 00:59:52,244 [7] ERROR InfoLogger - System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
2020-07-13 00:59:52,278 [7] INFO  InfoLogger - 断开连接
2020-07-13 01:00:19,170 [1] ERROR InfoLogger - System.Exception: load lua file failed
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 52
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename, String rootDirectory) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 63
   at Lazynet.LoginApp.LazynetAppManager.Builder() in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppManager.cs:line 72
2020-07-13 01:00:31,689 [1] ERROR InfoLogger - System.Exception: load lua file failed
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 52
   at Lazynet.Core.LUA.LazynetLua.DoFile(String filename, String rootDirectory) in E:\github\Lazynet\02\Src\Lazynet\Lazynet.Core\LUA\LazynetLua.cs:line 63
   at Lazynet.LoginApp.LazynetAppManager.Builder() in E:\github\Lazynet\02\Src\Lazynet\Lazynet.LoginApp\LazynetAppManager.cs:line 72
2020-07-13 01:04:24,163 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:04:24,181 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 01:04:24,182 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:04:28,482 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 01:04:28,767 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 01:04:31,956 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:04:31,999 [6] INFO  InfoLogger - liwei:123456
2020-07-13 01:04:42,359 [6] INFO  InfoLogger - 登录失败
2020-07-13 01:04:42,360 [6] WARN  InfoLogger - /User/Login action run slow 
2020-07-13 01:06:20,109 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:06:20,129 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 01:06:20,129 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:06:24,133 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 01:06:24,381 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 01:06:35,278 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:06:35,321 [8] INFO  InfoLogger - liwei:123456
2020-07-13 01:06:36,623 [8] INFO  InfoLogger - 登录失败
2020-07-13 01:06:49,217 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:06:49,217 [8] INFO  InfoLogger - liwei:123456
2020-07-13 01:06:49,283 [8] INFO  InfoLogger - 登录失败
2020-07-13 01:06:50,736 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:06:50,736 [8] INFO  InfoLogger - liwei:123456
2020-07-13 01:06:50,797 [8] INFO  InfoLogger - 登录失败
2020-07-13 01:06:51,237 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:06:51,238 [8] INFO  InfoLogger - liwei:123456
2020-07-13 01:06:51,300 [8] INFO  InfoLogger - 登录失败
2020-07-13 01:06:51,581 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:06:51,582 [8] INFO  InfoLogger - liwei:123456
2020-07-13 01:06:51,642 [8] INFO  InfoLogger - 登录失败
2020-07-13 01:07:18,823 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:07:18,842 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 01:07:18,842 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:07:22,793 [7] INFO  InfoLogger - 连接上服务器
2020-07-13 01:07:23,037 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 01:07:25,359 [7] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:07:25,401 [7] INFO  InfoLogger - liwei:123456
2020-07-13 01:07:26,723 [7] INFO  InfoLogger - 登录失败
2020-07-13 01:10:24,119 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:10:24,143 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 01:10:24,143 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:10:28,132 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 01:10:28,369 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 01:10:35,058 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:10:35,101 [8] INFO  InfoLogger - liwei:123456
2020-07-13 01:10:36,447 [8] INFO  InfoLogger - 登录失败
2020-07-13 01:12:09,800 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:12:09,822 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 01:12:09,822 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:12:14,001 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 01:12:14,253 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 01:12:17,429 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:12:17,471 [6] INFO  InfoLogger - liwei:123456
2020-07-13 01:12:18,853 [6] INFO  InfoLogger - 登录失败
2020-07-13 01:13:14,326 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:13:14,348 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 01:13:14,348 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 01:13:18,397 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 01:13:18,631 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 01:13:22,589 [8] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 01:13:22,632 [8] INFO  InfoLogger - liwei:123456
2020-07-13 01:13:23,978 [8] INFO  InfoLogger - 登录失败
2020-07-13 23:02:20,520 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:02:20,540 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 23:02:20,540 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:02:24,361 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 23:02:24,590 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 23:03:21,861 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:03:21,908 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:03:25,044 [6] WARN  InfoLogger - /User/Login action run slow 
2020-07-13 23:05:13,167 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:05:13,192 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 23:05:13,192 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:05:17,419 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 23:05:17,644 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 23:11:58,394 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:13:13,043 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:13:14,414 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:13:14,418 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:13:14,418 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:13:14,488 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:13:14,490 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:13:14,492 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:13:14,595 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:13:14,595 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:13:14,595 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:13:14,665 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:13:56,688 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:13:56,711 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 23:13:56,711 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:14:00,781 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 23:14:01,005 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 23:14:15,406 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:14:15,532 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:14:18,649 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:14:18,651 [6] WARN  InfoLogger - /User/Login action run slow 
2020-07-13 23:14:23,363 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:14:23,365 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:14:23,463 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:14:33,493 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:14:33,495 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:14:33,585 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:14:37,919 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:14:37,921 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:14:38,004 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:14:39,901 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:14:39,903 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:14:39,985 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:14:41,150 [6] DEBUG InfoLogger - ===recv data is {"RouteUrl":"/User/Login","Parameters":["liwei","123456"]}
2020-07-13 23:14:41,152 [6] INFO  InfoLogger - liwei:123456
2020-07-13 23:14:41,244 [6] INFO  InfoLogger - 登录失败
2020-07-13 23:26:22,581 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:26:22,633 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 23:26:22,634 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:26:27,782 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 23:26:28,451 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 23:27:22,559 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:27:22,611 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 23:27:22,612 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:27:27,909 [6] INFO  InfoLogger - 连接上服务器
2020-07-13 23:27:28,693 [1] INFO  InfoLogger - connect appmgr success
2020-07-13 23:28:04,331 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:28:04,382 [1] INFO  InfoLogger - >>>>> login  app start  >>>>>
2020-07-13 23:28:04,382 [1] INFO  InfoLogger - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020-07-13 23:28:09,566 [8] INFO  InfoLogger - 连接上服务器
2020-07-13 23:28:10,346 [1] INFO  InfoLogger - connect appmgr success
